### ISSUE TITLE
Update and make it compatible with new NextJs version 15

### ISSUE THREAD

**Issue by rftglyv** [ant-design/nextjs-registry#11]
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^14.0.0" from @ant-design/nextjs-registry@1.0.1
npm ERR! node_modules/@ant-design/nextjs-registry
npm ERR!   @ant-design/nextjs-registry@"^1.0.1" from the root project

**Comment by nunolemosdc** [comment]
☝️

**Comment by ahmad-punch** [comment]
Need this update as even if you use legacy peer dep flag to bypass and install, it still fails in the runtime. There are so many errors I'm facing. It's starting to look that I should move away from AntD for Nextjs 15.

**Comment by vitalijalbu** [comment]
> Need this update as even if you use legacy peer dep flag to bypass and install, it still fails in the runtime. There are so many errors I'm facing. It's starting to look that I should move away from AntD for Nextjs 15.

Ok thanks, do you have any idea on how much time it will require?

**Comment by selectDele** [comment]
请问什么时候能够兼容Nextjs15？

**Comment by funder7** [comment]
Check out the PR #12 
You can try with that with `npm i nilwurtz/nextjs-registry` until the PR is merged or another solution is available.

**Comment by heysafronov** [comment]
☝️

**Comment by pavlo-hadzheha** [comment]
I see there is the PR for this issue. 🫶 Please, merge it if it does the thing! Thanks!

**Comment by StrikerXx798** [comment]
+1, merge PR please!!!

**Comment by jellohouse** [comment]
please fix ASAP!! 🫶

**Comment by wizardlyluke** [comment]
Any ETA on this?

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/nextjs-registry/pull/12 and released in https://github.com/ant-design/nextjs-registry/releases/tag/v1.0.2
