### ISSUE TITLE
npm包里的类型是错误的

### ISSUE THREAD

**Issue by wleven** [ant-design/nextjs-registry#7]
### 这是npm包里的
![image](https://github.com/user-attachments/assets/17fcb5ce-2f36-4845-b3a0-f38745706085)
![image](https://github.com/user-attachments/assets/9229279a-658f-4c86-b759-cfecc64b8582)

### 这是本地构建的
![image](https://github.com/user-attachments/assets/5a8e099d-8c2d-4637-8c24-4b4866516795)

**Comment by wleven** [comment]
看起来好像是npm的包没有更新的样子？
@afc163

**Comment by afc163** [comment]
https://github.com/ant-design/nextjs-registry/releases/tag/v1.0.1
