### ISSUE TITLE
Release the latest code changes

### ISSUE THREAD

**Issue by ethos-vitalii** [ant-design/nextjs-registry#9]
Do you have any plans to release the current version of the repo? PRs #5 and #6 were merged in February and May but haven't been released yet.

I need to pass props to `StyleProvider` but because the release doesn't accept props for it, I ended up doing this:
```jsx
<AntdRegistry>
  <StyleProvider layer>{children}</StyleProvider>
</AntdRegistry>
```
If I understand correctly, it creates two instances of `StyleProvider`. Not sure if it's good or not.

**Comment by afc163** [comment]
https://github.com/ant-design/nextjs-registry/releases/tag/v1.0.1
